name: Build/release

on:
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm i
      
      - run: npm run build
        env:
          GITHUB_TOKEN: ${{ github.token }}
