name: Build/release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: npm i
      
      - run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: mac.pkg
          path: dist/*.dmg
